// src/lib/components/ProjectCard.svelte
<script lang="ts">
	type Links = { demo?: string; repo?: string };
	let {
		title,
		description,
		tags = [],
		links = {},
		image
	} = $props<{
		title: string;
		description: string;
		tags?: string[];
		links?: Links;
		image?: string;
	}>();
</script>

<article
	class="group overflow-hidden rounded-lg border border-[var(--border)] bg-[var(--card)] shadow-[var(--shadow)] transition-shadow hover:shadow-[var(--shadow-hover)]"
>
	{#if image}
		<img
			src={image}
			alt="{title} screenshot"
			class="h-44 w-full object-cover"
			loading="lazy"
			decoding="async"
		/>
	{/if}
	<div class="p-4">
		<h3 class="font-medium text-[var(--fg)]">{title}</h3>
		<p class="mt-1 text-sm text-[var(--fg-muted)]">{description}</p>
		{#if tags.length}
			<div class="mt-3 flex flex-wrap gap-2">
				{#each tags as t (t)}
					<span
						class="rounded border border-[var(--border)] px-2 py-0.5 text-xs text-[var(--fg-muted)]"
						>{t}</span
					>
				{/each}
			</div>
		{/if}
		{#if links.demo || links.repo}
			<div class="mt-4 flex items-center gap-4 text-sm">
				{#if links.demo}
					<a href={links.demo} class="text-[var(--accent)] hover:underline">Live</a>
				{/if}
				{#if links.repo}
					<a href={links.repo} class="text-[var(--accent)] hover:underline">Code</a>
				{/if}
			</div>
		{/if}
	</div>
</article>

// src/components/shared/ProjectCard.tsx
"use client";

import { motion } from "framer-motion";
import { ExternalLink, Github } from "lucide-react";
import Image from "next/image";
import { TechBadge } from "./TechBadge";
import { staggerItem } from "@/lib/animations";
import { cn } from "@/lib/cn";
import type { Project } from "@/data/types";

interface ProjectCardProps {
  project: Project;
  variant?: "compact" | "expanded";
  className?: string;
}

export function ProjectCard({ project, variant = "expanded", className }: ProjectCardProps) {
  return (
    <motion.div
      variants={staggerItem}
      className={cn(
        "rounded-xl border border-border bg-card overflow-hidden shadow-sm hover:shadow-md transition-shadow",
        className,
      )}
    >
      {project.image && variant === "expanded" && (
        <div className="relative w-full h-40">
          <Image
            src={project.image}
            alt={project.title}
            fill
            className="object-cover"
            sizes="(max-width: 640px) 100vw, 50vw"
          />
        </div>
      )}
      <div className={cn("p-5", variant === "compact" && "p-4")}>
        <h3 className={cn("font-bold text-foreground", variant === "expanded" ? "text-lg" : "text-base")}>
          {project.title}
        </h3>
        <p className="text-xs text-muted-foreground mt-1">
          {project.period}
        </p>
        <p className={cn(
          "mt-3 text-sm text-muted-foreground",
          variant === "compact" ? "line-clamp-2" : "line-clamp-3",
        )}>
          {project.description}
        </p>

        {variant === "expanded" && project.updates && project.updates.completed.length > 0 && (
          <div className="mt-3">
            <p className="text-xs font-medium text-foreground mb-1">Recent updates:</p>
            <ul className="space-y-1">
              {project.updates.completed.slice(0, 2).map((update) => (
                <li key={update} className="text-xs text-muted-foreground flex gap-1.5">
                  <span className="text-accent shrink-0">&bull;</span>
                  {update}
                </li>
              ))}
            </ul>
          </div>
        )}

        <div className="flex flex-wrap gap-1.5 mt-4">
          {project.technologies.slice(0, variant === "compact" ? 4 : undefined).map((tech) => (
            <TechBadge key={tech.name} name={tech.name} />
          ))}
        </div>
        <div className="flex items-center gap-3 mt-4">
          <a
            href={project.github_link}
            target="_blank"
            rel="noopener noreferrer"
            className="text-muted-foreground hover:text-foreground transition-colors"
            aria-label={`${project.title} GitHub`}
          >
            <Github className="h-4 w-4" />
          </a>
          {project.deploy_link && (
            <a
              href={project.deploy_link}
              target="_blank"
              rel="noopener noreferrer"
              className="text-muted-foreground hover:text-foreground transition-colors"
              aria-label={`${project.title} live site`}
            >
              <ExternalLink className="h-4 w-4" />
            </a>
          )}
        </div>
      </div>
    </motion.div>
  );
}
